// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtzrQonbWrokpRuXtx90oUpwyKhgMO3EQ',
    appId: '1:127788331220:web:c3d5384d534e306f2fcb41',
    messagingSenderId: '127788331220',
    projectId: 'peace-cf3ce',
    authDomain: 'peace-cf3ce.firebaseapp.com',
    storageBucket: 'peace-cf3ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bic35fYFoxRfpPYYh9zYGXZalXIVF20',
    appId: '1:127788331220:android:797d131490a86aae2fcb41',
    messagingSenderId: '127788331220',
    projectId: 'peace-cf3ce',
    storageBucket: 'peace-cf3ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ybI9vwZBqYrBOLbVN2i5tZ1AhdswlZg',
    appId: '1:127788331220:ios:37978d19825dbb452fcb41',
    messagingSenderId: '127788331220',
    projectId: 'peace-cf3ce',
    storageBucket: 'peace-cf3ce.appspot.com',
    iosClientId: '127788331220-pqmir2ttn02uoghjd0s24t833neeavmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.peace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ybI9vwZBqYrBOLbVN2i5tZ1AhdswlZg',
    appId: '1:127788331220:ios:37978d19825dbb452fcb41',
    messagingSenderId: '127788331220',
    projectId: 'peace-cf3ce',
    storageBucket: 'peace-cf3ce.appspot.com',
    iosClientId: '127788331220-pqmir2ttn02uoghjd0s24t833neeavmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.peace',
  );
}
